#!/bin/bash
COUNTER_CONTAINER=1
COUNTER=0
NAMA_CONTAINER="vina"
FILES="/var/lib/docker/aufs/diff/"
JUMLAH_FILE=0
let JUMLAH_FILE=`ls -1 /percobaan2/ | wc -l`
while [ $COUNTER -lt $JUMLAH_FILE ];
do
	CONTAINER_ID=`docker inspect -f '{{.Id}}' $NAMA_CONTAINER$COUNTER_CONTAINER`
	FILEX="$FILES$CONTAINER_ID/*_out.pdbqt"
	echo $FILEX
	for f in $FILEX
	do
		docker cp $NAMA_CONTAINER$COUNTER_CONTAINER:`basename $f` /hasilvina/
		let COUNTER=COUNTER+1
	done
	let COUNTER_CONTAINER=COUNTER_CONTAINER+1
done
